[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
inator = {path = "../../inator"}
bevy = { workspace = true }
bevy_egui = { version = "0.39.0" }
bevy-inspector-egui = { version = "0.36.0" }
log = { workspace = true }